### ISSUE TITLE
Unable to write to Emuflight?

### ISSUE THREAD

**Issue by MaxumFPV** [FrSkyRC/FrSkyOSDApp#1]
Im trying out a test build for the Matek F722-PX and Im unable to flash the OSD chip, Is there any chance someone could add Emuflight compatibility?

**Comment by fiam** [comment]
Hi @MaxumFPV. Thanks for your interest! Unfortunately we don't have the bandwidth to support every flight controller firmware ourselves. However, both this app and the OSD drivers found in INAV and Betaflight are open source, so anyone could port the required bits to Emuflight.

What needs to be added to EmuFlight is support for serial passthrough via `MSP_SET_PASSTHROUGH`. This Betaflight PR I wrote some months ago can be used as a reference https://github.com/betaflight/betaflight/pull/9274
