### ISSUE TITLE
Will not run with Windows 7 64bit 

### ISSUE THREAD

**Issue by Jetrell** [FrSkyRC/FrSkyOSDApp#4]
I have used this application with Windows 7 32bit and it opens and runs fine. 
But I can't get the App to open with a Windows 7 64bit machine, using either the 32 or 64bit application.

**Comment by alberto-frsky** [comment]
Hi @Jetrell. Could you please let me know the exact error you're getting? I've just tested both the 32bit and the 64bit variants on a 64bit Windows 7 VM and they seem to work properly.

![image](https://user-images.githubusercontent.com/70262824/99382954-276c2800-28c5-11eb-8ae6-f4e6be74a77e.png)

**Comment by Jetrell** [comment]
@alberto-frsky  Thanks for the reply.
After extraction on that machine. If I click on the App to open it. The waiting circle spins about a second, as if its trying to start.. but nothing happens.
I tried a few things. Reloaded another copy, run as admin etc. With the outcome is still being the same. 
I can still use the older 32bit machine for an update when required. 
I just thought I would report the matter, in case it was an issue with the application on that operation system.

Thanks
